LiteSQL: operations.hpp File Reference
operations.hpp File Reference
select<T>, intersect<T>, union_<T>, except<T>
#include "litesql/datasource.hpp"
Functions
template<class T >
litesql::DataSource< T > litesql::select (const litesql::Database &db, const litesql::Expr &e=litesql::Expr())
returns DataSource for accessing objects of type T
template<class T >
litesql::DataSource< T > litesql::intersect (const litesql::DataSource< T > &ds1, const litesql::DataSource< T > &ds2)
returns DataSource for accessing intersection of two sets of objects of type T
template<class T >
litesql::DataSource< T > litesql::union_ (const litesql::DataSource< T > &ds1, const litesql::DataSource< T > &ds2)
returns DataSource for accessing union of two sets of objects of type T
template<class T >
litesql::DataSource< T > litesql::except (const litesql::DataSource< T > &ds1, const litesql::DataSource< T > &ds2)
returns DataSource for accessing objects of type T that are in first DataSource but not in second.
Detailed Description
select<T>, intersect<T>, union_<T>, except<T>
Function Documentation
template<class T > litesql::DataSource<T> litesql::except (const litesql::DataSource< T > & ds1, const litesql::DataSource< T > & ds2)
returns DataSource for accessing objects of type T that are in first DataSource but not in second.
References litesql::except(), litesql::DataSource< T >::getDatabase(), and litesql::DataSource< T >::idQuery().
Referenced by litesql::except().